import React, { createContext, useContext, useState, useCallback, useEffect, useRef } from "react";
import type { ReactNode } from "react";
import type { Style, Color } from "../types/index.js";

// ---- Types ----

/** Visual variant for a toast notification. */
export type ToastVariant = "info" | "success" | "warning" | "error";

/**
 * A single toast notification.
 */
export interface Toast {
  /** Unique identifier (auto-generated by {@link useToast}). */
  id: string;
  /** Main message body. */
  message: string;
  /** Optional bold title above the message. */
  title?: string;
  /** Color variant. Default `"info"`. */
  variant?: ToastVariant;
  /** Auto-dismiss duration in ms. Default `3000`. Set `0` to persist. */
  durationMs?: number;
}

/**
 * Screen corner where toasts are displayed.
 */
export type ToastPosition = "top-right" | "top-left" | "bottom-right" | "bottom-left";

/**
 * Props for the {@link ToastHost} component.
 */
export interface ToastHostProps {
  /** Where toasts appear. Default `"bottom-right"`. */
  position?: ToastPosition;
  /** Maximum number of toasts visible simultaneously. Default `5`. */
  maxVisible?: number;
  /** Application content. */
  children?: ReactNode;
}

// ---- Context ----

interface ToastContextValue {
  push(toast: Omit<Toast, "id">): void;
}

const ToastContext = createContext<ToastContextValue | null>(null);

let nextToastId = 0;

// ---- Hook ----

/**
 * Push toast notifications from anywhere inside a {@link ToastHost}.
 *
 * @returns A function that accepts a toast payload (without `id`).
 *
 * @example
 * ```tsx
 * const toast = useToast();
 *
 * toast({ message: "Saved!", variant: "success" });
 * toast({ title: "Error", message: "Network failure", variant: "error", durationMs: 5000 });
 * ```
 */
export function useToast(): (toast: Omit<Toast, "id">) => void {
  const ctx = useContext(ToastContext);
  if (!ctx) throw new Error("useToast must be used within a <ToastHost>");
  return ctx.push;
}

// ---- Variant colors ----

const VARIANT_COLORS: Record<ToastVariant, { bg: Color; title: Color; text: Color }> = {
  info: { bg: "blackBright", title: "cyanBright", text: "white" },
  success: { bg: "blackBright", title: "greenBright", text: "white" },
  warning: { bg: "blackBright", title: "yellowBright", text: "white" },
  error: { bg: "blackBright", title: "redBright", text: "white" },
};

// ---- ToastHost ----

/**
 * Container that renders toast notifications for its children.
 *
 * Place `<ToastHost>` near the root of your app. Children call
 * {@link useToast} to push notifications.
 *
 * @example
 * ```tsx
 * function App() {
 *   return (
 *     <ToastHost position="bottom-right">
 *       <MyApp />
 *     </ToastHost>
 *   );
 * }
 * ```
 */
export function ToastHost({
  position = "bottom-right",
  maxVisible = 5,
  children,
}: ToastHostProps): React.JSX.Element {
  const [toasts, setToasts] = useState<Toast[]>([]);
  const timersRef = useRef<Map<string, ReturnType<typeof setTimeout>>>(new Map());

  const push = useCallback((toast: Omit<Toast, "id">) => {
    const id = `toast-${nextToastId++}`;
    const full: Toast = { id, durationMs: 3000, variant: "info", ...toast };
    setToasts((prev) => [...prev, full]);

    if (full.durationMs && full.durationMs > 0) {
      const timer = setTimeout(() => {
        timersRef.current.delete(id);
        setToasts((prev) => prev.filter((t) => t.id !== id));
      }, full.durationMs);
      timersRef.current.set(id, timer);
    }
  }, []);

  // Cleanup all timers on unmount
  useEffect(() => {
    return () => {
      for (const timer of timersRef.current.values()) {
        clearTimeout(timer);
      }
      timersRef.current.clear();
    };
  }, []);

  const ctxValue = useRef({ push });
  ctxValue.current.push = push;

  // Position styles
  const isTop = position.startsWith("top");
  const isRight = position.endsWith("right");

  const portalStyle: Style = {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    zIndex: 900,
    flexDirection: "column",
    justifyContent: isTop ? "flex-start" : "flex-end",
    alignItems: isRight ? "flex-end" : "flex-start",
    padding: 1,
  };

  const visible = toasts.slice(-maxVisible);

  const toastElements = visible.map((toast) => {
    const variant = toast.variant ?? "info";
    const colors = VARIANT_COLORS[variant];

    const innerChildren: ReactNode[] = [];

    if (toast.title) {
      innerChildren.push(
        React.createElement("text" as any, {
          key: "title",
          style: { bold: true, color: colors.title },
        }, toast.title),
      );
    }

    innerChildren.push(
      React.createElement("text" as any, {
        key: "msg",
        style: { color: colors.text },
      }, toast.message),
    );

    return React.createElement(
      "box" as any,
      {
        key: toast.id,
        style: {
          bg: colors.bg,
          paddingX: 1,
          flexDirection: "column" as const,
          minWidth: 20,
          maxWidth: 50,
        },
      },
      ...innerChildren,
    );
  });

  return React.createElement(
    ToastContext.Provider,
    { value: ctxValue.current },
    children,
    toastElements.length > 0
      ? React.createElement("box" as any, { style: portalStyle }, ...toastElements)
      : null,
  );
}
